### PR TITLE
Solved Issue #14 : Add Russian and Ukrainian as active languages

### PR DESCRIPTION
**Pull request by Darkboy17**
This PR closes/references issue #14.
## How has this been tested?

 I have fixed the issue as requested by adding the two languages, "Russian" and "Ukranian" to the Active language list.

Please take a look at the screenshot of the newly added languages.

activelanguages

To ensure if the languages can be translated, please have a look at the screenshot where I have selected "Russian" as underlined.

lang_sel_russian

Now to confirm, when I visit the link http://127.0.0.1:8000/orga/event/, it takes me to a page as shown in the screenshot below, which successfully translated the language to Russian.

page_russian_translated

Now, let us test for the language "Ukranian" by similarly following the above steps. 
Selecting "Ukranian" as shown in the screenshot below

lang_sel_ukr

Similarly, when I visit http://127.0.0.1:8000/orga/event/, I get the page in Ukranian as shown in the screenshot below.

page_ukr_translated

## Checklist

- [x] I have manually tested the functionality to cover my changes.
- [x] I have strictly followed the contribution guidelines and best practices.

### CODE REVIEW

**Comment by norbusan** [comment]
This is the same mess of a PR as the previous. Look at the commit.
image
Why are my commits, that are in development already, included in the PR?
Why are other issues included in the PR?

Can you please follow the advise I gave you and *ONLY* include the changes that are necessary?

**Comment by Darkboy17** [comment]
Norbusan, I'm sorry for the carelessness. 

In my first PR, I just worked on code and then commit and push my changes. 
Next, on github I visited the pull requests page, clicked on "Compare & Pull" and then "Create Pull Request".

Below is the screenshot of my first PR.
Screenshot 2024-02-20 at 19-28-42 Issue #17 fixed by Darkboy17 · Pull Request #38 · fossasia_eventyay-talk

As you can see, there's only one commit.

For the next issue I followed the same steps as mentioned above, but don't know why for some reason, many commits are happening when only my commits should be visible.

Am I missing something important here? Do I need to follow different steps for second PRs and onwards?

As for the recent advice you gave, I have cherry picked only the changes that are necessary and wasn't expecting to get the same mess.

Maybe I am missing something important here

**Comment by Darkboy17** [comment]
Can I just close all the messed PRs and start with a new PR? This time I'll be very careful.

**Comment by Darkboy17** [comment]
I'll close all the messed up PRs for now.

**Pull request closed without merging**
