### PR TITLE
[WIP] Sync up

### PR DESCRIPTION
**Pull request by norbusan**
Sync with upstream

## Summary by Sourcery

This pull request synchronizes the codebase with upstream changes, introducing new features such as detailed logging for deletions and new date validators. It also includes several bug fixes, enhancements to form validation and activity log handling, and updates to tests. Additionally, it removes unused utility files to maintain a clean codebase.

- **New Features**:
    - Added support for logging the deletion of events and organisers with detailed messages.
    - Introduced new validators for date and datetime fields in forms.
    - Implemented a new JavaScript file to dynamically update the page title based on the proposal title input.
- **Bug Fixes**:
    - Fixed an issue where event slugs containing malicious input could cause errors by returning a 404 instead.
    - Corrected the logic for filtering sessions in the schedule editor to include sessions starting and ending on the boundary days.
- **Enhancements**:
    - Refactored the activity log display and object link handling to use signals for better modularity.
    - Improved the handling of pending states for submissions, including visual indicators and scheduling logic.
    - Optimized the form validation by converting some methods to class methods and static methods.
    - Enhanced the logging output with additional context and formatting improvements.
    - Updated the review assignment forms to use a simpler and more intuitive format.
- **Tests**:
    - Updated tests to reflect changes in form validation methods and review assignment logic.
- **Chores**:
    - Removed unused utility files and functions to clean up the codebase.

### CODE REVIEW

**Comment by mariobehling** [comment]
Could you add this one as well, please? https://github.com/pretalx/pretalx/commit/f8d800d833a07081ac23a08d2963d0d0dfe49101

**Comment by norbusan** [comment]
> Could you add this one as well, please? [pretalx/pretalx@f8d800d](https://github.com/pretalx/pretalx/commit/f8d800d833a07081ac23a08d2963d0d0dfe49101)

Done

**Comment by mariobehling** [comment]
@sourcery-ai review

**Comment by mariobehling** [comment]
Solved by another contributor in the meantime.

**Pull request closed without merging**
