### PR TITLE
Fixes Change Submission Content Page into a) Content Page as a View b) Content Edit Page

### LINKED ISSUE #74: Change Submission Content Page into a) Content Page as a View b) Content Edit Page
### Problem and impact

The content page for reviewers currently shows the "Submission Form Edit Page". Expected: It should show a content page that is not editable and b) a content edit page (which is the current content page).

Screenshot from 2024-03-08 15-47-40

### Proposed solution / feature

_No response_

### Context or examples

_No response_

### PR DESCRIPTION
**Pull request by cbum-dev**
Added content page and an edit button to edit the content. 
Fixes issue #74 

## Checklist

- [ ] I have added tests to cover my changes.
- [ ] I have updated the documentation.
- [ ] My change is listed in the ``doc/changelog.rst``.

### CODE REVIEW

**Comment by cbum-dev** [comment]
Screenshot from 2024-03-15 21-41-00
Screenshot from 2024-03-15 21-41-09
Screenshot from 2024-03-15 21-41-20

**Comment by mariobehling** [comment]
I am unclear why there are three commits of @norbusan in this pull request.

**Comment by mariobehling** [comment]
Please check failing tests. Previously 6 tests were failing. In this PR 7 tests are failing.

**Comment by cbum-dev** [comment]
> I am unclear why there are three commits of @norbusan in this pull request.

Should I again make a fresh PR, because I don't know how these commits are their.

**Comment by mariobehling** [comment]
Ok, maybe a rebase could work, but if not try a fresh PR using the latest code, sure.

**Pull request closed without merging**
