### PR TITLE
Add option for sorting most popular sessions

### PR DESCRIPTION
**Pull request by lcduong**
This PR closes/references issue #161 . It does so by:
1. Add sort dropdown in session view
2. implement logic when sort with title/time/popularity

## Checklist

- [x] I have added tests to cover my changes.

### CODE REVIEW

**Comment by lcduong** [comment]
image

image

image

**Review by mariobehling — CHANGES_REQUESTED** [review]
Thank you. In the mobile view could you change the dropdown for popularity to an icon, please and move it in front of the "clear filters" icon similar to the previous eventyay version?

Screenshot from 2024-08-27 02-44-25

**Comment by odkhang** [comment]
image

Hi @mariobehling, updated as your request

**Review by mariobehling — CHANGES_REQUESTED** [review]
Thank you. I also realized the "Add to Calendar" option is missing in the mobile version. Please add the icon into the mobile version (without the text "Add to Calendar" next to the version info.

**Comment by odkhang** [comment]
Hi @mariobehling, updated

image

**Comment by hongquan** [comment]
Where is the source of *src/prhttps://bitbucket.org/hescar/markaz/pull-requests/155etalx/static/agenda/js/pretalx-schedule.js* file? Its content in this PR looks like the output of bundle process, not the source.

**Comment by odkhang** [comment]
> Where is the source of _src/prhttps://bitbucket.org/hescar/markaz/pull-requests/155etalx/static/agenda/js/pretalx-schedule.js_ file? Its content in this PR looks like the output of bundle process, not the source.

Hi @hongquan, pretalx-shedule.js is bundle of this plugin https://github.com/fossasia/eventyay-talk-schedule/pull/12

**Review by mariobehling — APPROVED** [review]

**Comment by hongquan** [comment]
The PR looks Ok, but unfortunately, it includes a code generated by https://github.com/fossasia/eventyay-talk-schedule/pull/12, and the code in eventyay-talk-schedule PR is still in question, I cannot approve this PR yet.
But this PR is OK to merge if eventyay-talk-schedule PR is approved.

**Pull request merged**
